### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by vweevers** [ironSource/node-generator-chrome-ninja#2]
Would be nice to add [livereactload](https://github.com/milankinen/livereactload).

**Comment by vweevers** [comment]
Yay, it works - at least for popups and option pages - with the addition of `"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"` to the manifest.

But it's incompatible with parcelify. Parcelify chokes on the `___livereactload_entry.js` file that livereactload inserts; it tries to read it from fs but it's not actually there. Should ignore the file somehow.

**Comment by vweevers** [comment]
Tasks:
- [x] Add gulp task that adds `content_security_policy` field to manifest in dev mode. And while we're at it, have manifest version follow package version.
- [ ] ~~Ignore livereactload file in parcelify~~ livereactload actually replaces each entry file in the browserify pipeline, but parcelify can't do its job without the original entry file. Hm.
- [x] Conditionally (when React is used) install dependencies required for livereactload
- [ ] ~~Exclude content scripts from reloading (don't load the livereactload browserify plugin), add explanation to readme.~~ Also: warn about default permissions being `http(s)://*/*`.

**Comment by vweevers** [comment]
What I cooked up is slightly crazy: for each browsing context (e.g. a background page or content script), a separate reload server is started. For all but content scripts, that's a `livereactload` server - when a bundle changes, the `livereactload` client in the corresponding browsing context is notified and some module in that context is hot reloaded. Due to chrome's security model, content scripts are handled separately with a `mini-lr` server. When the content script bundle changes, the background page is notified, which then reloads the entire extension.

If you generate an extension with all the options enabled, and then run `gulp develop`, you'll get four websocket servers:
- :4474 - for background page
- :4475 - options page
- :4476 - popup (browser or page action)
- :35729 - for content scripts (but handled by background page)

**Comment by vweevers** [comment]
Even better: content scripts can have hot reloading too. Like the rest, a livereactload server is started for the content script. The background page listens to this websocket, and passes messages on to the content script via chrome.runtime messaging. The livereactload client there can then perform the hot reload. I did some experiments, seems promising.

It does need more work, e.g. dealing with disconnects, multiple content scripts. And ideally, use just one websocket server - multiplexed for the different browsing contexts.

**Comment by vweevers** [comment]
See the [hotreload](https://github.com/ironSource/node-generator-chrome-ninja/tree/feature-hotreload) branch, which has hot reloading for all the moving parts. But I had to remove parcelify.

**Comment by kessler** [comment]
@vweevers Lets go ahead and merge to master

**Comment by vweevers** [comment]
Couple of things to do after merging:
- [x] Remove `version` field from manifest.json
- [x] In the generators build task, clean the `dist` folder before transpiling (to be sure that when we publish, old files like `chromereload.js` are not included)
- [x] Until we have something (like CSS modules) to replace parcelify (and with that, live reloading of CSS): remove LESS/SASS support, copy CSS files to `dist` and include `index.css` instead of `bundle.css` in HTML files
